// demo
export const DEMO_ADD_COUNT = 'DEMO_ADD_COUNT'
export const DEMO_LOGIN = 'DEMO_LOGIN'
export const DEMO_LOGINOUT = 'DEMO_LOGINOUT'
export const DEMO_REGISTER = 'DEMO_REGISTER'

export const TAG_GETLIST = 'TAGS_GETLIST'
export const CATEGORY_GETLIST = 'CATEGORY_GETLIST'


export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGISTER = 'USER_REGISTER'
export const USER_LOGINOUT = 'USER_LOGINOUT'