// demo
export const DEMO_ADD_COUNT = 'DEMO_ADD_COUNT'
export const DEMO_LOGIN = 'DEMO_LOGIN'
export const DEMO_LOGINOUT = 'DEMO_LOGINOUT'
export const DEMO_REGISTER = 'DEMO_REGISTER'

export const COMMON_GET_WINDOW_WIDTH = 'COMMON_GET_WINDOW_WIDTH' 
export const COMMON_OPEN_DRAWER = 'COMMON_OPEN_DRAWER' 
export const COMMON_CLOSE_DRAWER = 'COMMON_CLOSE_DRAWER' 

export const COMMON_COLOR_MAP = 'COMMON_COLOR_MAP'

export const TAG_GETLIST = 'TAGS_GETLIST'
export const CATEGORY_GETLIST = 'CATEGORY_GETLIST'

export const AUTH_OPEN_AUTHMODAL = 'AUTH_OPEN_AUTHMODAL'
export const AUTH_CLOSE_AUTHMODAL = 'AUTH_CLOSE_AUTHMODAL'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGISTER = 'USER_REGISTER'
export const USER_LOGINOUT = 'USER_LOGINOUT'