// article
export const ARTICLE_GET_CATEGORY_LIST = 'ARTICLE_GET_CATEGORY_LIST'
export const ARTICLE_GET_TAG_LIST = 'ARTICLE_GET_TAG_LIST'

// user
export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGISTER = 'USER_REGISTER'
export const USER_LOGIN_OUT = 'USER_LOGIN_OUT'
