// APP
export const APP_DEMO_ADD_COUNT = 'APP_DEMO_ADD_COUNT'
export const APP_UPDATE_WINDOW_WIDTH = 'APP_UPDATE_WINDOW_WIDTH'
export const APP_SWITCH_SIGN_MODAL = 'APP_SWITCH_SIGN_MODAL' // open sign modal
export const APP_SWITCH_UPLOAD_MODAL = 'APP_SWITCH_UPLOAD_MODAL' // open upload modal
export const APP_UPDATE_RESULT_MODAL = 'APP_UPDATE_RESULT_MODAL' // open result modal

// article
export const ARTICLE_GET_CATEGORY_LIST = 'ARTICLE_GET_CATEGORY_LIST'
export const ARTICLE_GET_TAG_LIST = 'ARTICLE_GET_TAG_LIST'

// user
export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGISTER = 'USER_REGISTER'
export const USER_LOGIN_OUT = 'USER_LOGIN_OUT'
